# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sortVars <- function(term, vars) {
    .Call('_mpoly_sortVars', PACKAGE = 'mpoly', term, vars)
}

getMonomialStrings <- function(poly) {
    .Call('_mpoly_getMonomialStrings', PACKAGE = 'mpoly', poly)
}

combineMonomials <- function(poly) {
    .Call('_mpoly_combineMonomials', PACKAGE = 'mpoly', poly)
}

tidyTerms <- function(poly, vars) {
    .Call('_mpoly_tidyTerms', PACKAGE = 'mpoly', poly, vars)
}

removeZeros <- function(poly) {
    .Call('_mpoly_removeZeros', PACKAGE = 'mpoly', poly)
}

reducePoly <- function(poly, vars) {
    .Call('_mpoly_reducePoly', PACKAGE = 'mpoly', poly, vars)
}

mpolyMult <- function(e1, e2) {
    .Call('_mpoly_mpolyMult', PACKAGE = 'mpoly', e1, e2)
}

mpolyPow <- function(e1, e2) {
    .Call('_mpoly_mpolyPow', PACKAGE = 'mpoly', e1, e2)
}

